# 为什么要学习Pytorch？
pytorch是基于Python的科学计算包。


*   作为NumPy的替代品，可以使用GPU的强大计算能力
*   提供最大的灵活性和高速的深度学习研究平台



## Tensors(张量)


*   张量的使用和Numpy中的ndarrays很类似, 区别在于张量可以在GPU或其它专用硬件上运行, 这样可以得到更快的加速效果
*   张量如同数组和矩阵一样, 是一种特殊的数据结构。在PyTorch中, 神经网络的输入、输出以及网络的参数等数据, 都是使用张量来进行描述。




### 张量初始化

In [2]:
import torch
import numpy as np

# 1. 直接生成张量
data = [1,2],[3,4]
x_data = torch.tensor(data)
print(x_data)

# 2. 通过Numpy数组来生成张量
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

# 3. 通过已有的张量来生成新的张量
#   新的张量将继承已有张量的数据属性(结构、类型), 也可以重新指定新的数据类型
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

# 4. 通过指定数据维度来生成张量
#   shape是元组类型, 用来描述张量的维数, 下面3个函数通过传入shape来指定生成张量的维数
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2429, 0.9053],
        [0.6666, 0.3372]]) 

Random Tensor: 
 tensor([[0.7562, 0.0888, 0.9699],
        [0.0447, 0.2522, 0.4461]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 张量属性
从张量属性我们可以得到张量的维数、数据类型以及它们所存储的设备(CPU或GPU)。

In [3]:
tensor = torch.rand(3,4)

print(f"shape of tensor:{tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

shape of tensor:torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 张量运算
有超过100种张量相关的运算操作, 例如转置、索引、切片、数学运算、线性代数、随机采样等。更多的运算可以在这里查看。

所有这些运算都可以在GPU上运行(相对于CPU来说可以达到更高的运算速度)。如果你使用的是Google的Colab环境, 可以通过 Edit > Notebook Settings 来分配一个GPU使用。

In [11]:
# 1. 张量的索引和切片
tensor = torch.ones(4,4)
tensor[:,1] = 0      # 将第1列(从0开始)的数据全部赋值为0
print(tensor)

# 2. 张量的拼接
#   可以通过torch.cat方法将一组张量按照指定的维度进行拼接, 也可以参考torch.stack方法。这个方法也可以实现拼接操作, 但和torch.cat稍微有点不同。
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

# 3. 张量的乘积和矩阵乘法
print(f"tensor.mul(tensor): \n{tensor.mul(tensor)}")
# 相当于
print(f"tensor * tensor: \n {tensor * tensor}")

# 4. 自动赋值运算
#   自动赋值运算通常在方法后加"_"
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor.mul(tensor): 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor * tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
